/// Flutter icons DataBaseMonitor
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DataBaseMonitor
///      fonts:
///       - asset: fonts/DataBaseMonitor.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DataBaseMonitor {
  DataBaseMonitor._();

  static const _kFontFam = 'DataBaseMonitor';
  static const String? _kFontPkg = null;

  static const IconData arrow___top = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_2 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
